version: 2
jobs:
  build:
    docker:
      - image: cabiri/ct-deploy

    steps:
      - checkout

      - run:
          name: Export Envrionment Variables
          command: >
            echo ${CTP_PROJECT_KEY}

            export CTP_CLIENT_SECRET=$(aws ssm get-parameter --name /api/commercetools/${CTP_PROJECT_KEY}/secret --with-decryption | jq -r '.Parameter.Value')

            export CTP_CLIENT_ID=$(aws ssm get-parameter --name /api/commercetools/${CTP_PROJECT_KEY}/client_id --with-decryption | jq -r '.Parameter.Value')
            
            export CTP_AUTH_URL="https://auth.sphere.io"

            export CTP_API_URL="https://api.sphere.io"
            
            export CTP_SCOPES=$(aws ssm get-parameter --name /api/commercetools/${CTP_PROJECT_KEY}/scope --with-decryption | jq -r '.Parameter.Value')

            export CTP_SUBSCRIPTION_ACCESS_KEY=$(aws ssm get-parameter --name /api/commercetools/${CTP_PROJECT_KEY}/subscription_access_key --with-decryption | jq -r '.Parameter.Value')

            export CTP_SUBSCRIPTION_SECRET_KEY=$(aws ssm get-parameter --name /api/commercetools/${CTP_PROJECT_KEY}/subscription_secret_key --with-decryption | jq -r '.Parameter.Value')

            export TF_VAR_terraform_bucket=$(aws ssm get-parameter --name /api/commercetools/${CTP_PROJECT_KEY}/tf_bucket_name | jq -r '.Parameter.Value')
            
            cd ./config

            terraform init

            terraform plan -var "subscription_access_key=${CTP_SUBSCRIPTION_ACCESS_KEY}" -var "subscriptoin_secret_key=${CTP_SUBSCRIPTION_SECRET_KEY}"

            terraform apply --auto-approve -var "subscription_access_key=${CTP_SUBSCRIPTION_ACCESS_KEY}" -var "subscriptoin_secret_key=${CTP_SUBSCRIPTION_SECRET_KEY}"
