version: 2
jobs:
  build:
    docker:
      - image: cabiri/ct-deploy

    steps:
      - checkout

      - run:
          name: Export Envrionment Variables
          command: >
            export CTP_PROJECT_KEY=lego-poc

            export CTP_CLIENT_SECRET=$(aws ssm get-parameter --name /api/commercetools/lego-poc/secret --with-decryption | jq -r '.Parameter.Value')

            export CTP_CLIENT_ID=$(aws ssm get-parameter --name /api/commercetools/lego-poc/client_id --with-decryption | jq -r '.Parameter.Value')
            
            export CTP_AUTH_URL="https://auth.sphere.io"

            export CTP_API_URL="https://api.sphere.io"
            
            export CTP_SCOPES=$(aws ssm get-parameter --name /api/commercetools/lego-poc/scope --with-decryption | jq -r '.Parameter.Value')

            export CTP_SUBSCRIPTION_ACCESS_KEY=$(aws ssm get-parameter --name /api/commercetools/lego-poc/subscription_access_key --with-decryption | jq -r '.Parameter.Value')

            export CTP_SUBSCRIPTION_SECRET_KEY=$(aws ssm get-parameter --name /api/commercetools/lego-poc/subscription_secret_key --with-decryption | jq -r '.Parameter.Value')
            
            echo ${CTP_PROJECT_KEY}

            terraform init ./config

            terraform plan ./config
